version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "12:00"
    groups:
      frontend-dependencies: # You can name this whatever you like
        patterns:
          - "*" # Groups all updates in this directory into one PR

  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "12:00"
    groups:
      backend-dependencies:
        patterns:
          - "*"
          
